#!/usr/bin/env python3
import numpy as np
import random

import mountain_car_evaluator

TENSORS_ENABLED_LOL = False
# TENSORS_ENABLED_LOL = True


if TENSORS_ENABLED_LOL:
    import glob
    import os
    import tensorflow as tf
    tf.enable_eager_execution()


if __name__ == "__main__":
    # Fix random seed
    np.random.seed(42)

    # Parse arguments
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--episodes", default=10000, type=int, help="Training episodes.")
    parser.add_argument("--render_each", default=500, type=int, help="Render some episodes.")

    parser.add_argument("--alpha", default=0.1, type=float, help="Learning rate.")
    parser.add_argument("--alpha_final", default=1e-3, type=float, help="Final learning rate.")
    parser.add_argument("--epsilon", default=0.2, type=float, help="Exploration factor.")
    parser.add_argument("--epsilon_final", default=0.03, type=float, help="Final exploration factor.")
    parser.add_argument("--gamma", default=0.99, type=float, help="Discounting factor.")
    parser.add_argument("--tiles", default=8, type=int, help="Number of tiles.")
    args = parser.parse_args()

    # Create the environment
    env = mountain_car_evaluator.environment(tiles=args.tiles)

    # Implement Q-learning RL algorithm, using linear approximation.
    W = np.load("W.npy")

    # import base64
    # Wbytes = b'co18+KuNEsDEsWBYpNkRwJb6bO80axHAJAmplHaAEcCwRnZNR+ATwCdvHxlKJRTA7RQaSuibFMDlY+pGfoYWwHa4MOMLsxbAJXX2lUNxFsBKQPFOuK4WwGAhndCdHhXAMHvidcZaFcDM8CyiWJsUwO4kb50RHRLA/o0NKgATEMDxucwUb4UQwOgyUfc0IA/ArGphcBSr8L9iPmA2LX7zv1AmNFxrQAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/ER3M6vlFcBeSg3LseIVwJugSB1iWRbAz978856dE8CuZGZ5CdoTwLG9vvv9WxPAXrqu4XgeF8A5yKge/cIXwNYS6byL4hbA9YrTiUS0G8CFjy8eIzocwN+79+MMeBvAtdD8SxWBG8AhToDd0UkbwDJ9JsWMJxrAOpDt+YZgEsD/YpY5FI8SwOvEYBFCXRPATkka6QAhDcAkKWeKbmELwOHaX/LGLQrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA150n4dTwFsBnnB8RJxUXwGr/Pc7sMhfAXlr1ZvW7FMAiC+A8I9UUwC/OPpG5hBTAmwfftkkxGsADQEDZDIsawCtueQOm8RrAEh4HiWF+IcBI6VtmOKMhwM5H6GPlpiHAWofCvVdrIcD3qUF+DQchwKC06lqIzCDAQF89P94rH8A9RRzNzD4ewErX3EET/RzAIyLkTU1vDcDRRkb/fxgNwKOriA1F5g3APmfw1CrBBMBO4cnybygEwMEV9qpcdQTA5qhoMjo0FMCikMALHWkUwNyI36satxTAuHEEHnBxFcCc7RkeSGcVwBiMpLLsMxXAU0wT96kyGsBC8kk74bsZwPl+zFDlixnA2ztv/ZMsH8Do87AqcIoewKNpfjeDCh/AsVZ4jOGKIMBhWQk+yz4gwFZncQQPOSDAk+g+KY7qHsDeLUCNXckfwBzPbkm5oyDAdScvO20aFMBaLWdCVhATwEJGlQr0zBPAs/O9HXWhAcB5zUQsyvsBwDBaGnoL4QHA/ZWDiSG8+797XMrVUtn6v+2dGLC5Bvq/hiUqgwiQFsDz6k+N40UXwMBVUHfVkxfAPih/V8jOF8Capg/7pBQYwFqrnNHGQxjAnjkA0xcPGsCEk/tzZ3cZwHkTkKl1thnAi2cpNqYCG8AYhS7QAZcawMEDRoDsuRrAF1Sl7o5oHMCUINyhVIYdwKp/QJyGZx/A0lNpCB6dD8CkVSdq6psNwL3zgaaO8w7ABoV+cpVd+7/NLgMb1ND7v0ZgLUVIxf6/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMsaTLf0SDcB4jvX7VQIMwKcTCYh8rAvAIe61+3jRFsAOyJEmynIXwOFfpd05thfA+PogaA+iGcD2EZfKv08awKEf8q/cdxrA8UUGvPpJGsApwi3aWgkbwKd7siNfZB3ACXAZJkxYGcCoyEj08skXwCNo97lv/RTA9wrJvD6L/b+fOxX+XrP5v2jR4S/Wivi/tx/fHmnY7r+vhmoscEnxv1oV6gfRbPa/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMtt5hXkB8BTwMAmYCkHwL6ZUzZpbwfA+Sw/5h25FMDHULhxFrYUwCjbn2SNvBTAZFkJhyQmF8AvLo199ukWwCk2uiOk0xXAv8fVBG2T/L8jXB98NnT5v++NpDZ5yPy/rHygxYjD9L99ZusliKrzv1yGRgdaqvS/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUXATLvmQQL8AAAAAAAAAAAAAAAAAAAAA7v/8rzbr9r8K9Iv1WWr4v4prZZp+3PW/VNcokyCmAMDR8mfOeNgAwGq9bBtIcPy/IIGsMT2/6b+Z/q+faFjqv3PuP10uSuq/cVZEQgqX0r9T4ZtPHhbUv9htgsDl69O/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5sNdY4+G7L9FVH+i3iHqv+oW27wXBuq/5xnQWVBnEsARkkJCmUMXwHNuOrVq8RfASIgO7NsaEsDRt99GvCkTwKKoamoe+RLAKMAYjMN5FMB6XEU5iYIUwNU3K1EFpBTAYluPjHs9FMDQS/zYAggUwNaqghVwORLA87DGoBenDsD7KuTICsUOwJh/OTgV9gzABrzwJ2RQ/7+ZzLyM2XMAwDrchGkqrQbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiXqYpUXwCsDqSWlkT3IJwC6QXwf72QjAwQKk4QjcEcCJ4WOaZWMSwDGHHMeH+BHA2MmurOxOFcBSMVrMtcgWwIHJSZR/7hbAUeBU5m4aGcBBLdG4mHMZwFrziwuAGBrA6z9FnSNDGsD1dGidV9YZwNndM9/zhhnA7ByL0LtFFMCvcQ7FhF0UwHr5L/R24BTA/+vnLI+wDMBruz0EdzMNwPGxuRnh4wnAGPO9pYLY97+4pSyQKwj8v9alw3i8PwbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcssWacZTEMCVvQADwKQPwP8tO2DAXQ/AmAl3t3JsE8AqSdRyq50TwPdKB85P/BPAyO1pXKlHGMCKYO8WJx0ZwMOnNGkTXBnAhCPo46P8H8C8A6u4y2QgwDJwTW7cyCDAouO+e31BIcDT5xP8TBAhwHnYa9MoPCHAB0lwK1QAIMApXWMd7bIfwBLcqEwmGCDABR0Rs2B4FcAPcRox/PYUwOw1IB1EQhTAslOFXGkSCcCsyLU/gxIIwLbVvVTbzgXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAi8ebNLFSC8CjLB9RhHsHwL3NT6c1hQfAqhwXXv2NFsA3E0P+rwoWwGyuWF5bzxXAH8UrCaXFGMD9aIInTQ4ZwJ9e0sh2/hjAamZRJXvqHcDWQc7J+UsdwDBGApMNuB3A0rSRpXJyIMBEAD2zm6MgwByJrWvsSCHAh537zgUDH8APSD52IDwfwB6ucJ4dRB/ADAEfgf+bHcDsPW5vpoIbwNfA5/N2RhrADDZ31PupCcBnj2t+H48JwObiLYcjWwXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQK2Gn23Xk7+3Mlz4yyGqv+5rFsV0TsC/xeX7El6dFcBTNZNxwU0XwEF1E4Wj6hfAMjZKA/u9F8Dr5C5Ofb8XwEnwvLuFGhfAsK4TpVYjGcAvKSmMI5QYwOBiOkDkBhnA4WOF/cz+GsD+q9/FHn4awM6W8U42/xrA6TS4yMS/GsCEywGlD78bwKYt6mAEPRzAlREj8cOqG8AJMItt7ZkZwF47rnPLmRfA6ZSghXhFA8AXaXYT1z0DwOiZgbUszP+/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPhdgBizSAcCu004wmcL7v+9qjp+Olfq/qSEAnsmXFcA9OpxpM9gWwIcX5YvTNRfAPEWmiPg4GcCyBx0xmn8ZwNKmz7UH0xnAWKGd1e5xGsCA9umbsNUZwBE6hdI/lBnAsyC+7ZJMHcDPj64RrMUdwDvr5XiGWB/AG+QLBUAoCMBSVIvfvLUGwLw8yURHoQjAdVyAzfyB+b9tttsolRT8v8rXL991S/2/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+HTEBvHNAMCi4y3IO9f+vyrRsKbrev2/4QWx3rioFMBOoAwG9fcUwDwgiyXe3xXA3Our7OyYGMAqVwUHB34YwM/3k9GObhnAStC5sJsLEMD7iW8eQmkMwMwPk6/N4wnAhvkt9myz9L9kKHgJ4LHzv+dleV6H5vS/d8HzIghd6b+yMUh9Fj/pv4PNkq/UJ/G/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRUpCN+b7r/fwYwK25Xwv9gtyXwHj+6/xTyPUNIYCMBv0T3KvysIwMynMbeEAQfA5r+4uA9j8r9591Tbc8Lyv3+cQ5s08+6/gMEmAz8E57+o3Rr5DE3jv7SgdPExuuG/qsKnP+c0XL+KUtfBSOSfvzYInYGf/Lu/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARf22rkP2EsBOaxnLS7ASwCLb/TBrfBLA2r06gnOtEMAH25x82fIOwNnoH3WxxA/AyYO17p92EMBEsVirjD0SwKHhy6GpPhLAeOSy6gHVE8CWnoTh5yMUwGecTe+2fxLAdSqQofpzEsCpMlqmZ54SwHZ5aFKCkA/AhB2rchJVAcDFkordMWMCwKZujOxilgrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZcs8W1+lyr/xjNEv81vMv8MLp+68M7a/I/p6jcrMFMATgRkMdxMXwN7EaPX0tRbAZ22mvhbMFMBAVfVjn9sUwJWw8peYQxXAD0t6Tc/WFcCmNgv2tRkWwF85OHuGRBbACTDF1Q1qGMChPic0vdMXwL0hSk56/RbAFBki6HCOFsBwGPeOZCkVwIR2/AI9eRXAc/Q2eMXbDcDAwUccQQ4MwL2C6SobBw3A5nbhokCPBcAw7eUOdsYFwHC7u2pYRgbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPq1inNUX9b/2n3TOnVn1v72KfiqimPK/NMzKfo29FcCuliry4j8WwOsjBB/iZRbA2/hWmVtVF8CyU2yjhdgXwFAdV0N5wxfAZ/3ct4+AG8Cx4mIpFhQcwMyYbs5MmhzAnpYBYpjWIMCugNOFYUohwE9B/DFHCiHAGwahqpfgIMDGvaqMNY8gwKPhNBBdByDAECvz66maGMB7qeVQVBsZwNnkJ9zf3xfAvMhk3voaCMCmjSAmonIIwMu+E0TGnAbA737/1CMW7L/FHj46pxPxv4xtwF+2KAHAMOAyHXp937+L5Th265/av9i7UFXe7t2/7Ksp7TEJF8ARR5HEt8cYwFqZRkRxexjAIaevuv6qFsADyyiCLHAWwJSX62TppRbAabLwKtGpG8CUelIesw0cwHinTuZNMh3AAo587sGiIMDguH2PF8MgwIqHIqqEoCDACzD4aPzAH8BJDRtWLSsfwABvxklblB7AnpcXdXRKIMBd3kw7vUAfwP7RMjoZ0x/AqqUxBcMMCsB/vp4X4uMJwCeESj2KlwrA02pN8R7t+7/AFHgE1DD8v76Vzs7MCwLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN2w5tkbhEsCJqtk8MBMSwJcMrDlISRLAOX/Muz3CF8AZqHm3ZmEWwPh5mfAt+hbA3Sn+jIMmGMBQ8XXxHyEYwCmOxsXXRxjAljc9WpUAG8C0Ii+4MdcawK1o0bCrQhrAcgSYsVS/G8AD8GxCelwbwAqAY26uFRvAI4tZXzIZHcDFxEBE9NMewOsyD/yuCx/An3fHRD2NCMAVMzKjkN8FwGTu4aVI5wXAFmbe95ej+r/5BOPrdiX6vy5W/x9kIv+/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF8TD61/s1r8M8cD94TDJv1fRSOywttK//sNl3jVpFMCR/ZQ54yUWwDUMRWe11RbA2nfffEIyGcAEzPEnJbwYwC72XbpHsxjABYt71+2gGsDYT5RWQGMawIv5CEm2nhrAGaLaA8xMG8BPnaW3ZLwdwFYfY8Y1mh7AeHX0YRFcF8CMl2TaeaoWwAhDaqbjpxTAA3OqM2EU+7/QQ4l4ZnH5vzy5B0PhOPi/R9wRLNOT278yIHk3tj/cvyKizs+kde+/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9ZhmfdU48b8OwcW4a6fqvzXIWbdLPOe/1/WtQmezEsBkWB9YQeQTwCoJbbgNQBTACEXYn26+F8AM+o9bumwXwFQk3Yl37RbAZWjhjla8GMBCy9L8oCEYwMKO0l1V8BbANK0q6sTA/r8evfXPZ9L5v4LuSfujQPm/VIqD+URk9b/cD/XLG27zvxVGwBSKnvO/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPeSKyLls3b+O7OG7ObDXv0rclTv/9eC/q5GRTtnDCsBJwdMV9dsLwJk8G3mvxQvA/j8z2jG9AsAaau6CRFIAwJWiXYEVZPW/HKdvfQmg8b9eOHB9xVHxv/RPhBvTrfG/KCU+Xmd1zr//6v7DhtHQv2PnI4CeyNK/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnN2+seyqAcDb6zWpFM/+v9DW4qNNxP6/rwIGkYMUDsAtpg3dE/gQwHlJxo5VYBHATE3GCXaND8BlUKnAVhoQwJWSt7mjXxDAYBux5rPUEcAy70PdZyoSwM+jn+nlHBLALSoh1xzaD8BS+gVv6hEQwPb4V9j1GBDABH1I/+WXC8B+UjeoUkELwPIqjNsNNQzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAehfu5xj4EcBqypBngToRwMnz4qRjXhDA0PNql/xfEMCpDYJmR7gQwBQ+SrM3SBDAOMRvvbTTE8BSCgY8FyoVwMLFRLn23BTA3MNaU5WwFsDRiE87QkwWwOwf7pDo0xbAErJ7puWUFcCCklsTCRIVwNZc8rXnxxXAUUz2I5bXEMBXdD+7fkwQwOlUlQbB/w/AC68Xyj6OC8C0JPCIaa0LwFex+OruVwzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAb2MVFAmiE8DIPM1y7VQUwOIIPJksKBXAdRNN0s8yE8Bf9G66LhETwNig5Itb3hLAprR3y/mtF8CqYJ8UW3QYwPGPT47QdRjAz4qFzYpqIMCuwhZ8N/0gwCw17uc6+SDACE88Zf88IMBU7Ds0bmggwLpA0cIoRyDA5GYyfCQDG8BO3mi1nJgbwDVhKxGdVRvA3doqRbpiDsB7fJQnniQOwOUiFDhLZQ3A8iFEPm4+AsA1R50QPu4CwBsZ+VbvAAXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAuwg6gI5KE8BqX4A/WI0TwMFjmRLP9BPA8XUH2He0FMBfY9o61DwUwMgWeRxdXxTAwn2qhKmPGcAVidvgvLkZwDH+3A2O1RnA137LkuYjIMD1OVtxResfwC8Lt0J66R/AIhWc9cQnIcB8rlv6IbcgwJU1iXdSLiDA48ELW+xGIMAoeTebv3wgwOvXhnsBKiHAHqLQBoR4FsD3zf85bigVwLRiy9mvfhXAGTo7wqp/BcA3eL1/gQ4FwHUWIhpsdQPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2xLHXY31AsC+ErNGUNoCwFs8aRDoMQLAcb4YR2HHFsDmXsy8JbQXwBZJDTpc4hbANP7FW8dcF8Cg5hNo51MXwK3A4zDKRhfAOglZEf5OG8CSNEGsVkIbwL97gcO+HxvAvf9BbzVbHcDqPALrOsQdwG+eMppJMB7AJRbK51pwHMDnMLsNTIMdwEEEemk9Oh7Ab9iMn/TZFsCC7KpSiecUwNk6W+va2RTAXxgfBR/qAMBWS+2SVSYBwBaQloocUP+/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeeCQerU2EcDnV/2Xw+wRwAAUbXaLGxPAL3liKCsnGMAETzQJNZ8XwNqY+rFh5hfAaCp0+uNrGcBopODndkYZwAl/2nqBjhnA3E4Hgp/dGcD9mUh4TNYZwFFAzgKSGxnAaqbxmkTIHMDseHlVvdAdwDmxvSb1JR3AUpF8O5AHB8DTl8ctZ7YDwDU3a9JZEATAd7So0u09+L+TB9hUEev5v/ZwdTfE3v6/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWqLp6Uncz7+l2LTo5l+qvxnOuuWu2qO/hPjMhR8NEsAQoqEQoHASwM3IVA9fSBLA4HmcsNzLF8DiB04r68AXwEd+Gwbm2hfAPuxzRsg/GsAXqn4ITy0bwAwyA/ieURzAtxEEjQzdDcDMKhFwi40KwMpQo25xywvAzfIvJ/ny9L83VBAt/Uj2vw34GS0Q1Pa/rjZH2Alv27/rQR2v7mHgv2dRtsVLXe+/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaTk2sZ5Srr+ThqnGtG+1v1MEAq1Qbae/WyYUXFz4B8AtmrTaoOwHwCQ32ji83gbA+YcdnQMVD8CKEhz1oUUNwMF0Mi8LQQrAvQaNmTlq9L8PyLjJjbHxv/0rYepMl+6/4k0GSQ1X6L9BttBYpULnv8z+L6gX8+O/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdKhKh8hquvwAAAAAAAAAA/6aoqABaE8CsRvoz8NcSwInHCgF6LxLAf0qqpX7TEMDyge3LcUQOwKPx9l1frg3A21k+xQd9D8Bz+CS6ipgOwP5UfSMIVhDAziwKutFnEMB2/NcE7YkQwNeoSe+FGxHAneDAq7WnD8BNfHIFu3sPwN8A3nLGFBDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMtLowq9++L+NchscCKb3v1nW/KpWpve/b0wQ6VCiEcAr+3slXdYSwLbffZWtkxLANBNLUBwBE8CYgoqgfwQUwNf+Q4jdLhTA5BTg2EW5FMDsZvB9vp4UwGwb5jPX9hTA6BarjLcjFMCrC5hopNITwBMNpdDmrBTAx2l/aQFREMCYxygYeCEQwDmUVb0tpxDAguL836g6DsBiHH2WbBINwCbCoZfCrgrAZGNqXZpK87+xpW2++B32vzZKO6YvIgbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYeO25nwKCcCqFUvDF4YIwOlUDczfyAjAp5S+QRsWEsDeCGV2rpASwO2+pWp7LRLAqCD7LnklFsCkKcL7PzcXwDxznRdOrRfAAs8Sv0fUG8Ds6VuAok0dwCv/I29S2x3ABbML65q8H8DiR4BtSk8fwE/orDvzyR/Aj15jjWJ7HMCR0HNrGQMdwMBPaMEiCxzAUUsogHdCEsAl5Ptkes4SwD2nsY+YYxHAU7VNjCUgCsA8HDOnjAgJwN/tzFOOcgbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAliCuRcE5B8BEfQ4T/xEFwAm5cP5qvwXAMdsjZjY/FMCSOrw57L8UwKSr2BcbrhTA2COR3//2F8A36K/M11AYwGYzNklfeBjAzyvCtNJAHcAWh/uFdpcdwOuW0O7lKx7AbKlzglwNIcDSrOTVKUghwAvOLNq8KiHAEaMmhcCVH8C26U3bqjAgwL53QnVwAyDARCLmgL2LHcBkhz9N3W0cwEPPRnSzphrAxbLqLDcEC8DumDqBFJwKwDuhRdfSVgfAziTQG6WUu7+e4jMbll/Jv/+xafzp4uS/+je23d+c2r9h6Hartk/gv6krs6wjMda/x4C93c0QFsAmRYg26SkYwFqbb5piKBnAAGlm1GljFsARvs/k2okWwM8ofMsR3BbAB1c8eclmGcCZW96BaLMZwIlqKkvvJRrAwh8ZcRjWHMAmQlGrFtscwJi/6SZGPx3AExXh61HaG8AE7+kxE0wcwMn3jDnDcRzAU20u3TPUHcAktY0heTwdwICdoL1/aBvA9MCSKu36BsAkSpxTR7EFwCn+hk6nrwPAPaMcmz8Y6L9MX1P1rwHrvzcUSsucsPO/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2cMOu64ZCMCo0Adz1CUHwJ72m2jd/gXAOzv++jECF8A8v8ebn84WwGEFivN1IhfApFAwxAJPGcC/DQy+zsQYwBiG/QiYtRjA9JY8LMHIGsAJdt4bC4YawPd8iHfWsxrAvIXClivUG8DRNh104HUdwMh7+U5iTSDAeE06jbPFFsABzI9HoW4UwHCqQCyTqRPAXxzMXGm5/r9lazxCojD+v2aa7cb7lfa/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWp+EUBMyDMDzwZOyRtALwNhhEOr1xgvAP97MXMdmFsAYYQQ8G8kWwNO4EJAJbBfAzJrSWqu8GMDxF1YXyagYwOYXuozf2xjAEmDamUwEGcB3VIGvze0WwC13nvjxPBbA9HIfsirF/L9YvhhSxDT8vxj6JTYZl/S/fSN8kVDq87/j8nlXkT31vydX2O+sb/K/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANI9VL9voV2/WanNI3o1A8AN42Ih+loCwBT/SvkNkAHAxfTpbYSCEsBB2fXawCwTwC3hy+J+zhPAwmrTNDrp+r9d0seFm9nzv7AjBTVGlvS/8sj/lOtQ779Kot/uSDrwvxTjt5AdGe6/wWtXEWVF07+HfXu6AqvXv2z2QAL/suG/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxYJnAJng0r/YiZE09NLYv7dd0fkB0Ne/MLGdnZQ/5b80pCab4Hnmv9aJ9SBzFeW/ZLfhuDpNxL9RhydSYRrGv7vWg5ZmnNq/LE4SqydNfL/t/Evq9wV2vwnfXUFoeLO/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2q97OHN4CMAbPFG0VYIFwIKiobGyBQTA/kN9pUNqDMCYQe9EHg0OwLa7L1wE+w3AyZCOL6ZVDsD9fhtuRAYNwCEtc7itkgzAABhBkStYEMB1GuVMuoUPwKMd3BEvExDAR22jWJbuCsAKMmdI/1cKwN0g5pxOsgvAuBrS4xsO978eZ0Tf99z5v+u0n6R3qwfAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4bWkmXgE8CLGpWee9YTwFlPUApHrxPA/5wgxlhSEcAPgU6xMzoQwNmotmzu3g/Af3NsnzxsE8DjGrNVO48SwDlmrX71dRPA5x8FAaoxEsAD6LgBy28TwB5V88YW/xLAtIEP7uphEMD6d5EWMCcRwM0SG1vdCBHAANz9bW3fDsBWZ4zO8xAPwCCatou5FgrAm/VLCKOH/b899jQKzC78v5JXeyJvvQTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYpC5r0ccu7+GlIa8JMLGv4KB8TKUmby/hWhmTDx/FcB/m6C2CAsXwOP6hrhidxbAhR4QAwR+FMBRG4n6Z2sTwJ6fsxvkuBPAqsBaQqGLGMAk57Wy26QYwE8L5hWR+xfASfhouWvaHsCb83fl4dUfwL4Y0LNO6R/AkugEhXPeHcCKVaHKlTMewNklRw4REB7A5gMM0CeHFsDkW6IHfBcWwPDsI1R74RTA+Y5Vn7WmCMAxvjqxwSYIwJ29IJb/YQbAkDgJgEbx5L9XAcPypjzov1e9aq73Ofq/7rG7Eyq4qb85TwBtT6W1v01K4iSFxpq/xlZzNjxAFsBVTWK20vAXwLhOLrWvpxjAtbKof7/jFMClHtFJ2H0UwFHzIecGCRXAObuiZffzGsCJGsqJjAAbwGJtPmnnsRvAyO2PjfVRIcCRXGUut6whwKbDmBXHtyHA5bUnNj1OIMBw8/1JFBggwJ2PSrmqDSDAiesffH+fH8BR8Ot6uxcfwHechEf6/R7Ay5/5DMBfDMC3G0mVlFoMwFolvVn/tgzAbBLzsB+J/78TqCfvLfn/v+YPK9SzrgHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZM4ODHHlE8DCKkJBi84TwPQkmO6dUxTAZM1pD8HgFcAXJEu0C6AVwLhsxCNo7xXAd+YmB7GiGMBiiMGEI7cYwIoXvIqxcBjAz8n6/RfyHMDrvy63hbwcwNVtxI3LixzA9/oh1A3LHsBBYOG7nFgewFicdTlJWh3AfcCal6myHcDPc7PmBJEewKummC3Xmx/A+EWG2dPtEMC+Sv4yO4UQwHcsDGTGlg/ArvpwN0IX/78U4CJMaRP9v0L8ZATiU/2/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhs4DU7dI7L858k10xqzqv6W2z4BEWuS/E179OwhfFMDs5N7ZRksXwDJAsIrSwRjAHOQVjevNGMDFJTm0J7oYwEHlZ+HOtRjAtq44ubP2GMCilHOJUJoZwGQTk6D4eRnAlscoXPnVGcDNt6Rof8QZwC1L3aXbDhjANa6InIQ2HcDTcJPNr1ccwLBUKLfcBhvAXywKVEEyA8CXavZeHJcBwOt3IBNk6wDAb6S9Wwwm+L8L5BmgTV/3v+kSccPR1fe/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALHFLr59GA8A24PkY0IgBwAwWd0BWOwDAZ2C0Dm8rFcBJhCD0xSUWwINgIcRVJBbAMGYtSqSTGcCBFmGHMIcZwLQ70o4BSxnABVlBvtcNG8CAj/gnkokcwI6CNr+fhB3AFtH3lJT4DcDUm1OGJFgLwPzmQkcXmAjAeTQM9xBg+b8o1HowVPD3v0iLWdCH6fW/oWCL08KlMb+WJA1TiP1xvy0pIVJ/rMC/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHcd/Ik029r/VeTQvi4v2vw0+Wo1SN/a/jCxRb1AREcD6GGfByTERwIa2gzs3oBDAfNzfxzSKDcDruLWVAo4JwHwGhhorrQbARCrdVlEo8b8kT0ETNtjyv7+g4m7p9vO/XXe8LJa25r82NoiwDLTnv1J3XdTqo+W/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPyIGFm8s478x0h9s2nPiv8gBNY6cJOC/EK0A2tI19L99fPuw4DP0v3I2sDaSmva/EV8mi6qG2L8UMt6sB6TWv/kocBTnLdy/uOQQWSDCv782cpj4E06+v2xiNz27I72/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUu/9WBeg0r/7M9cwWC+zv1Pmml76BkO/TdtUow84EsAaBFcunuUSwNQ8II+rzxLArXDwDt6oEMAhxNQ+zpENwMHIO8YkcwzARSAufhwADMCxQy3Gz4oJwNuQ6qf0SArAOW4q7hkRCcBNIJVThX0JwNdQgjuNoQvAx4jJZPjB+7+qVSin0SUAwOFbpwhWjQjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqpncxys0BsD9l1jm5r8EwAdJaDFnEAbA+QgMLl27D8DbtS/TZkENwI1NL+dO7AzAZR3akcNVEsCyyD1DEIMSwIanUhXDnhLAbSUI4GyDE8Bg69YbR1ETwPBAjZAd6RLA6lvYBpZEEMDuBwiUXZ4QwIGH+p4LdhHA/yBLMcsKD8DmqGPOMcYNwM8CipGYSwzAwfv2DTNqBsCpCvO8n00GwLAZZiQy3AbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4t9fGW/fEMCEeTLzUOIQwJ08+goUJxHA4kXh9nLHEMAjn8f5V5gQwMecRb6osRDATAHVdFQSFcDLh5vTOR8VwK+V0NwJkBXACotnAtAyG8BXDtjpFZgcwKwNJjQrhx3AHzsE6VtPHcCUL5kPO+YcwBapr0jFVB3AzecZlB58GMAxY2n7KocXwHjMQWq3lRfApf6RZMWWC8DSS6b0xgoLwMmFcv+sownApMlxir1hAcCMEUjcSHsCwCwUCl/tcATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALKVYOAGvEcAChWcWKnkRwMnPFvEXyBHADt0UAYOgEsAOV8HifAkTwFP10Sm3IhPA/GigVML9F8Bi5mcW9YwYwKSvoHONkRjAInnc6eRbH8Ck0+lBY0cgwFZJP0fKNyDA+vFr5wQGIcAIu/xMGusgwKhp2cXiqiDA587cGlOdIMA2awwk3HcgwNEa/zw2WyDAs5BfNmFgFsBeu6rRlVwWwAc77+NI0hTA4pyaA3Y1CMDSvvDN4PYGwKKTgw/5owXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAc4p99H9OBcBlBj7NSV4FwHqYmhIioATAYCS/FmxgFcDKeXQtiV8WwD/KRgVH4RbA8FTcrpslF8CAj5PqBloXwOWQVkL/dBfA5ftpNEmtG8Al/cRnT2IcwK92nK3eLBzAEZDid/qmHsCgb9dTJV8fwNNLSkbOcR/AWWn22vJZHMDVvKCDxVQdwHVMDNxeeRzAV/ytyQgJHMAuj/qM2w4ZwPR9/UXeLxjAE+lNJrnVBsBEO71Ll9wGwNXS+w2MdgPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2FSARCHBXL/35UOHYJqZv3TE1QWTtpW/zQSATxF2E8CafjlZVEwVwM2ndaFEZhXAObYdLHwbGMDotfuLplAXwOmKUBOkERjAjoASJ//MF8BoA0sCl5UYwNJKFLZtFxnAe0S5IfruGcBhI1lmhZYZwAs+bIZNvBnAXmdrpwFzG8CjDE/cwjAdwCy/F6OpQh/AL0NnxgZ8E8DOPQ5VdWYSwKXqOZGQ9xHAmZ7zUde2/L8D+IlyKrH8vxi28Xpdgfu/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1O/G9DLA4789foAR3Yrmvz5ppPzaouC/QnDrQ1uqE8C8McdROOcVwEeiaYtMuBXAwBuXN7ODGMCsGnttxXAZwIRUgEs71RnA+Tut0DWYGcA35ZpZq1EawLAGj8v8vxrA61OuPVMgGsDQo0Z6Fu8WwGD+q8mDhxXA3QDZau17+L9PHqJMFu75v5qshVpehPa/8tyeLgoN87/6NfOogO7zvyLjyJJnefa/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8hjaNVZl6L9mUmtowHHmvz2se4aE9+W/aBDms9UREcAALTuJByYRwCs6gDttLhHAHdvDr2pdFMCv2M/j3aIUwEA48Le0ZxTA1sQ4pnOb+b+c72HhwRH2v+8l2v2Pufe/MCWfboIh879aTSGtycLyv+wy3P/eG/G/LQzmN4n4h79hh2nHwoGXv7HB4Ah3u9S/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2uaBon+Z0r+XEmTv7pzZv+ilpy1qZ9G/1PCSp5hE+7+1V1lOejr5v5kL3r9+nvy/sAPSUxgG67+qnqG3eMHnv+ZtKon8tuO/3us8vIEk1L9qlOwTr+zZvyzpUvqD5tG/AAAAAAAAAACfkqFnZDdDv+SFZu+U//y+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArOeZmnGGCMCGrPnpTKIEwGrk+wQBWgPAGQd87OBmDcAPixYhN78KwB7wVzRWSgrAIYkpjRa3DMBlbNHnsUYJwLnEDvSSHAnAcvHk+7QkBcCZ+9i0dDsFwAkrTJ42Lg3AT93mkPMqAMCYUCpkhrsAwJq1rMK5UQnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGhyUXGslmD9t5Bs/CEy8vwAAAAAAAAAAdb+gS31CEsBx071fzOgTwG5X6Nqe4RPA9swU5HKREcBl/5nM67sPwNvsrb+c6g7AKx9ao6kyE8DfuDPv+lsRwFFMHgdvqhHASoqXjEriDsAn+fQeNJoPwCzJfy1ZcxDAuDSwTbZhDsAuUOHB2k4NwOuZ+uJ8/AvAzTsSFd7bC8BcuTzIGYUMwGnR5aXFnwnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC9CqG78s/L+xoagbjAz9vyNx30Ei3fu/kAX2lbZkEsCxcJkUDZUTwISVx4jy4hPAFpjrFXR0FcBHASuCcgYVwNGb+H3KKRXAvESNdXXMF8Cb3liqqYsXwCWJ38GFBhjAOzM9Lm97G8AZcZttCvYbwEka/M5aqxvAY7lJOC+tGMCxqRrNx3EYwDSinHGUVhfAGiEFmC4HD8DUan1guQAPwJhO9W/7Vg3ADpUpHTV6CMAThHtWn3wIwIlvtCIYnATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAReS1v0mSAsASb8J0otUBwPzKfYLXwADAtsjcUtlJFMCWcULCInEVwOu9KI01EhXAGQOvhkE8F8D35uOIzMUXwIX3npGV0xfAaKlLhg3uHMBk/lXmCDEdwLJgLi9Sfx3ARy9xghUQIcDIo5aCCikhwB+RoTzm6CDAQCvw1VhrIMCYUSrl6fUgwGkQ0FHzGyDA7kQhTLU1HMCLlP+6+gEbwLSYhvCLDxnAGRV40MYyCcAAt7CQ/GAJwIaCtOSe1wXA0y/ccCvS7L898iXzX4TwvwRuY57/ZADA5XN9lp9A5L+6uGGTKknev5h8tBRtq92/lXBq2eV0FsDtK9KOZwcYwF3mp86VThjAWXQrHeI6FcBB65ZiPVwWwH34LhN7BBbAaKSAVnVVGsDop1KF/RwbwAfbD60zBRvAu88fHuPzHsDDvCl7hWwfwHUycL4RAiDAyPEsYsikHsAh0aUYkHEewDqGYb9b/B3ArgzGQBhWHsBbm3HWBNgewHG4nxdgNx/Az2tYOpPjBsBUypCist0EwMPVfL86dwTAXcBBQO0++b+CkdYPyUT6vy600G3NTwDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApRIygVw1D8CsO50Ny34NwCdJC7X/AQ7A2/NzILI6F8CKwLX6wOoWwGK6rPXscxfAMHNeXVmPF8B2PodYE2oYwEpbepzo3xjAOcac9muGGcA6vCQTaVQawGaHMSQF5xrAf8jD4ifyGcAebyrTgVkawF9ApIrO1BnAXZNf3DXqHMBXEESjQ9EbwPBh8aFFKxrAi1L/CmrfAcAH1O5C9TwBwNjX+cGeev6/n5SWuAxr7L8gWraML0Hsvwd7x41Zjfa/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAApGqy7FuVnL+I2Ae9wlWrv7B/K5tAT6y/l8Nr+BhVEcD6kibY+j0SwMzJOCNYPRLAiMKmNwPiF8BfhdoHW9kXwPzT16JWCBjAOwTupmz8GcD/1LOdWuMZwLTYl+zGnhnAq2HZ5wR6HcAmYA0OCpkewByEdxW5rx7A0ZrUzGpRCsBugkUSONEJwFk/3XWNzAjADtyHwz2R+L+Pr/0Fkh34vwpeVtfUyvi/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQOA6oyO6uL/+YIFQyMK1vyrHUk9m8K6/agpSCHiBDsC3fIpe7f4NwERyHc4ZMBDAfV4AF1XIFMBBGQK7ZZAVwBTM1YeQVhbAtACGbXVcDcDOwwvivosLwP+i1X7k3QrA95oeb4PY87//FveFZ2n0v3qT/fUAJPO/8CRhOjbM5r8iulHyaUXov3VuEBHbDuy/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANqGRmi5Nub84JmOiuO6mv9dOZbKJFLm/YDQ32nFI/L84C7MNApv7v9Q1HjfFwfy/js+vnbnw9b9O6Rcp8frzv14We5sym/G/D4No2M04479efr3sSzjhvxarBW9RVeC/yLk3iKgSq7+sWUhbWAC7v8Rsl7bjO8a/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    # W = np.copy(np.frombuffer(base64.decodestring(Wbytes), dtype=np.float64).reshape(631, 3))


    # W = np.zeros([env.weights, env.actions])
    epsilon = args.epsilon
    alpha = args.alpha / args.tiles

    if TENSORS_ENABLED_LOL:
        maxname = max([int(name.replace("logs/", "")) for name in glob.glob("logs/*")])
        logdir = "./logs/{}".format(maxname + 1)
        print("Logging into {}".format(logdir))

        global_step = tf.train.get_or_create_global_step()
        writer = tf.contrib.summary.create_file_writer(logdir)
        writer.set_as_default()

    def onehot(x):
        result = np.zeros(env.weights)
        for i in x:
            result[i] = 1

        return result

    def Q(state):
        return onehot(state) @ W

    best_score = -1000.0

    evaluating = False
    while not evaluating:
        # Perform a training episode
        state, done = env.reset(evaluating), False
        while not done:
            # if args.render_each and env.episode and env.episode % args.render_each == 0:
            #     env.render()

            Qsa = Q(state)

            # TODO: Choose `action` according to epsilon-greedy strategy
            if random.random() < epsilon:
                action = random.randint(0, env.actions - 1)
            else:
                action = Qsa.argmax()

            next_state, reward, done, _ = env.step(action)

            # TODO: Update W values
            gradient = (reward + args.gamma * Q(next_state).max() - Q(state)[action])
            W[state, action] += alpha * gradient

            if TENSORS_ENABLED_LOL:
                global_step.assign_add(1)

                # with tf.contrib.summary.record_summaries_every_n_global_steps(5000):
                if global_step.numpy().item() % 1000 == 0:
                    with tf.contrib.summary.always_record_summaries():
                        tf.contrib.summary.histogram("W", W.reshape(-1))
                        tf.contrib.summary.histogram("gradient", gradient.reshape(-1))
                        tf.contrib.summary.scalar("gradient_norm", tf.norm(gradient))
                        tf.contrib.summary.scalar("epsilon", epsilon)
                        tf.contrib.summary.scalar("alpha", alpha)


            state = next_state
            if done:
                break

        # TODO: Decide if we want to start evaluating
        if args.render_each and env.episode and env.episode % args.render_each == 0:
            rewards = []

            for i in range(100):
                state, done = env.reset(evaluating), False

                total_reward = 0
                while not done:
                    # if i == 0:
                    #     env.render()

                    action = Q(state).argmax()
                    state, reward, done, _ = env.step(action)
                    total_reward += reward

                rewards.append(total_reward)

            mean_reward = sum(rewards) / 100.
            print("TOTAL: {}".format(mean_reward))

            if mean_reward > best_score:
                best_score = mean_reward
                np.save("W", W)

            if mean_reward > -100:
                print("DONE!")
                evaluating = True


        if not evaluating:
            if args.epsilon_final:
                epsilon = np.exp(np.interp(env.episode + 1, [0, args.episodes], [np.log(args.epsilon), np.log(args.epsilon_final)]))
            if args.alpha_final:
                alpha = np.exp(np.interp(env.episode + 1, [0, args.episodes], [np.log(args.alpha), np.log(args.alpha_final)])) / args.tiles

    # Perform the final evaluation episodes
    while True:
        state, done = env.reset(evaluating), False
        while not done:
            # TODO: choose action as a greedy action
            action = Q(state).argmax()
            state, reward, done, _ = env.step(action)
